In [8]:
import pandas as pd
import numpy as np
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,accuracy_score,precision_score,confusion_matrix

In [9]:
df = pd.read_csv('C:\\Users\\sravy\\Desktop\\ml lab\\zoo_data(For Decision Tree Program).csv')

In [10]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [11]:
dlf = DecisionTreeClassifier()
dlf.fit(x_train,y_train)
y_pred = dlf.predict(x_test)
print("Decision Tree Classifier Accuracy:",accuracy_score(y_test, y_pred))
print("Decision Tree Classifier confusion matrix:",confusion_matrix(y_test, y_pred))
print("Decision Tree Classifier classification report:",classification_report(y_test, y_pred))

Decision Tree Classifier Accuracy: 1.0
Decision Tree Classifier confusion matrix: [[9 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 4]]
Decision Tree Classifier classification report:               precision    recall  f1-score   support

           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00         4
           3       1.00      1.00      1.00         1
           4       1.00      1.00      1.00         1
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         4

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

